import { MigrationInterface, QueryRunner } from 'typeorm';

export class Init1716114667174 implements MigrationInterface {
  name = 'Init1716114667174';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "Events" ("globalPosition" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "messageId" character varying NOT NULL, "messageType" character varying NOT NULL, "streamId" character varying NOT NULL, "streamPosition" integer NOT NULL, "data" jsonb NOT NULL, "metadata" jsonb NOT NULL, "timestamp" TIMESTAMP NOT NULL, CONSTRAINT "PK_81997eb6a97d72528c4e1a9bbf8" PRIMARY KEY ("globalPosition"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "Events"`);
  }
}
